<?php /* @var $block \Perspective\NovaposhtaCatalog\Block\System\Config\Collect */ ?>
<?php /* @var $escaper \Magento\Framework\Escaper */ ?>

<script>
    require([
        'jquery',
        'prototype'
    ], function (jQuery) {
        var collectSpan = jQuery("#collect_span_<?= $escaper->escapeHtmlAttr($block->getTranstlitedName())?>");
        jQuery("#<?=$escaper->escapeHtmlAttr($block->getTranstlitedName())?>").click(function () {
            collectSpan.find('.collected').hide();
            collectSpan.find('.processing').show();
            jQuery("#message_span_<?=$escaper->escapeHtmlAttr($block->getTranstlitedName())?>").text('Processing');
            jQuery.ajax({
                url: "<?= $escaper->escapeUrl($block->getAjaxUrl()) ?>",
                type: 'post',
                cache: false,
                data: {form_key: window.FORM_KEY},
                showLoader: true,
                error: function (response) {
                    collectSpan.find('.processing').hide();
                    collectSpan.find('.collected').hide();
                    var resultText = 'Error';
                    resultText = response.status + " " + response.statusText;
                    jQuery("#message_span_<?= $escaper->escapeHtmlAttr($block->getTranstlitedName())?>").text(resultText);
                },
                success: function (response) {
                    collectSpan.find('.processing').hide();

                    var resultText = '';
                    if (response.error === true) {
                        resultText = response.message;
                    } else {
                        resultText = 'Success';
                        collectSpan.find('.collected').show();
                    }
                    jQuery("#message_span_<?=$escaper->escapeHtmlAttr($block->getTranstlitedName())?>").text(resultText);
                }
            });
        });
    });
</script>

<?= $block->getButtonHtml() ?>
<br/>
<span class="collect-indicator" id="collect_span_<?=$escaper->escapeHtmlAttr($block->getTranstlitedName()) ?>">
    <img class="processing" hidden="hidden" alt="Collecting" style="margin:0 5px"
         src="<?= $escaper->escapeUrl($block->getViewFileUrl('images/process_spinner.gif'))?>"/>
    <img class="collected" hidden="hidden" alt="Collected" style="margin:-3px 5px"
         src="<?= $escaper->escapeUrl($block->getViewFileUrl('images/rule_component_apply.gif')) ?>"/>
    <span id="message_span_<?=$escaper->escapeHtmlAttr($block->getTranstlitedName()) ?>"></span>
</span>
